// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbjriasakctsmlfyxvum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ianJpYXNha2N0c21sZnl4dnVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzA4MzksImV4cCI6MjA2MTcwNjgzOX0.yAgNmXkN-AOnnrUHBlR6BgF0KF4wwCcy0BLb_Et4Q7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);